# Documentacao Numpy
https://numpy.org/doc/stable/reference/index.html
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.size.html

In [22]:
import numpy as np

In [23]:
#Array de uma dimensão
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
one_dimensional_array
#print(one_dimensional_array)

array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])

In [24]:
#Array de duas dimensões
two_dimensional_array = np.array([[6,5], [11,7], [4,8]])
two_dimensional_array
#print(two_dimensional_array)

array([[ 6,  5],
       [11,  7],
       [ 4,  8]])

In [25]:
#Preencher arrau com zeros e uns
array_zeros = np.zeros(5)
print(array_zeros)

array_ones = np.ones([2,4])
print(array_ones)

[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
#Preencher array com uma sequência de números[limite_inferior, limite_superior]
#O intervalo é fechado no limite inferior e aberto no superior
sequence_of_integers = np.arange(5,12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [27]:
#Preencher array com números inteiros aleatórios
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[55 62 92 99 64 98]


In [28]:
#Preencher array com números float aleatórios
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)

[0.33447145 0.32882797 0.0021574  0.38997958 0.27250296 0.37270567]


# Operações Matemáticas com Numpy

In [29]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.33447145 2.32882797 2.0021574  2.38997958 2.27250296 2.37270567]


In [30]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[165 186 276 297 192 294]


# Tarefa: Criar um dataset linear
* Criar um array "feature" com uma sequência de inteiros de 6 a 20 (inclusive)
* Criar um array "label" onde :
label = (3)(feature) + 4

In [31]:
feature = np.arange(6,21)
print(feature)

label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


1. Adicione algum ruído ao dataset

Para que o dataset pareça mais real, insira um ruído aleatório a cada elemento do array Label. Adicione um um valor ponto-flutuante aleatório entre -2 e 2.
random.random()*(b-a)+a

In [32]:
noise = (np.random.random([15]) * 4) - 2
print(noise)

label = label + noise
print(label)

[-0.40227146 -0.71765873  1.56506601  0.7959488   0.80169909 -1.35952415
  0.55643958 -0.51594477  1.97829011  1.6488004  -1.31753132 -1.40586765
 -0.01022262 -0.10750501  0.88350887]
[21.59772854 24.28234127 29.56506601 31.7959488  34.80169909 35.64047585
 40.55643958 42.48405523 47.97829011 50.6488004  50.68246868 53.59413235
 57.98977738 60.89249499 64.88350887]


In [33]:
label.size

15